[versions]
agp = "8.10.0"
appcompat = "1.7.0"
core = "1.6.1"
gradle = "8.10.0"
junitJupiterApi = "5.12.0"
junitPlatformLauncher = "1.12.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
materialVersion = "1.12.0"
mockitoCore = "5.14.1"
runner = "1.6.2"

[libraries]
androidx-core = { module = "androidx.test:core", version.ref = "core" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterApi" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiterApi" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
chesslib = { module = "com.github.bhlangonijr:chesslib", version = "1.3.4" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

